### PR TITLE
Modified fibbonacci using dynamic programming in JAVA #hacktoberfest

### PR DESCRIPTION
**Pull request by meghnabajoria**

### CODE REVIEW

**Review by G1Joshi — APPROVED** [review]

**Comment by meghnabajoria** [comment]
Thank you for merging my PR @G1Joshi :). How will it get accepted for Hacktoberfest?

**Comment by meghnabajoria** [comment]
Hi @G1Joshi . When will it get accepted for Hacktoberfest? :)

**Comment by G1Joshi** [comment]
@meghnabajoria your PR is merged it's means that it was eligible for hacktoberfest.

**Comment by meghnabajoria** [comment]
@G1Joshi Thank you :)

**Pull request merged**
