### PR TITLE
Binary_Search.py

### PR DESCRIPTION
**Pull request by LaxmiNyamagoud**
Added Implement Binary Search #8

### CODE REVIEW

**Comment by LaxmiNyamagoud** [comment]
> Congrats on making your first Pull Request in the C0D1NG Organization! 🥳

Thanks!

**Comment by LaxmiNyamagoud** [comment]
can you merge this PR

**Comment by LaxmiNyamagoud** [comment]
can you merge this PR?

**Comment by LaxmiNyamagoud** [comment]
can you merge this PR?

**Review by G1Joshi — APPROVED** [review]

**Comment by G1Joshi** [comment]
Welcome to the world of C0D1NG 🚀

**Comment by LaxmiNyamagoud** [comment]
Thanks!

**Pull request merged**
